services:
  postgres:
    image: postgres:17.4
    restart: always
    container_name: postgres-docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NatsumiChan
      POSTGRES_DB: postgres
    network_mode: 'my-network'
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 4g
    command: [ "ollama", "pull", "mistril" ]
volumes:
  ollama_data:
  postgres_data: